### ISSUE TITLE
conda activate gpgLabs-environment

### ISSUE THREAD

**Issue by yangdikun** [geoscixyz/gpgLabs#106]
![image](https://user-images.githubusercontent.com/5066933/50165400-df7ea800-031f-11e9-8a33-886677eeb498.png)

I got a new computer and was setting up gpgLabs. environment.yml file was successfully created. But if I want to activate it, I got "Could not find conda environment: em-apps-environment". Then I tried gpgLabs-environment instead, and that was running ok.  Is that a simple mistake or I am misunderstanding? Shall we change "source activate" to "conda activate"? The latter seems the recommended syntax.

**Comment by thast** [comment]
you are Dikun. This is likely a copy-paste typo. Use gpgLabs-environment, as specified in the file environment.yml itself. we will fix the manual.

**Comment by lheagy** [comment]
Thanks for fixing this @thast! I believe that the difference between `conda activate` and `source activate` is windows vs mac, can anyone else confirm? or it might be the version of conda installed...

I am on a mac, and I use `source  activate`. We might want to add both use-cases to the readme (once we figure out which goes where)

**Comment by thast** [comment]
`conda activate` is now the preferred way on any platform. `source` may become depreciated in the future. See stackoverflow link:

https://stackoverflow.com/questions/49600611/python-anaconda-should-i-use-conda-activate-or-source-activate-in-linux

**Comment by thast** [comment]
I suggest changing the readme to `conda activate`

**Comment by thast** [comment]
PR #107
