### ISSUE TITLE
GPGlabs Tasks

### ISSUE THREAD

**Issue by dccowan** [geoscixyz/gpgLabs#51]
**Tasks for GPGlabs**

Mag Apps: Dikun and Dom
Seismic Apps: Sarah, Mike
GPR Apps: Devin
DC Apps: Thibaut
EM Apps: Devin, Seogi, Dikun
Upgrade IPyWidgets: Thibaut

**Tasks**

•	Set imported txt or npy files as input (i.e. no hardwired path in functions). Paths should be specified as variable in notebook, and entered in widget function.
•	Code should not automatically create and export files to unknown directory (i.e. don’t create png and export to hardwired location)
•	Clean up code importing
•	Get rid of need for files like “importMag.py” as well as “flatten” the structure.
•	Make python 2 and python 3 compatible

**Comment by dccowan** [comment]
- GPR: Code has been rewritten to fit the proposed format.
- EM: Code has be rewritten to fit the proposed format.

**Comment by yangdikun** [comment]
Most items done. Still need to figure out the path.
